### ISSUE TITLE
PlatformViewRegistry getter is deprecated

### ISSUE THREAD

**Issue by moinkhan780** [nycm1989/nImagePicker#1]
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
Height of Platform View type: [XvGWvxQbgkeDVg==] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [XvGWvxQbgkeDVg==] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.

**Comment by nycm1989** [comment]
Thank you for the comment. I have updated the plugin to work with web instead of HTML, and the dimensions are now required. If you use .expand, the height and width will expand to the parent widget. Best regards.

**Comment by nycm1989** [comment]
> The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead. Height of Platform View type: [XvGWvxQbgkeDVg==] may not be set. Defaulting to `height: 100%`. Set `style.height` to any appropriate value to stop this message. Width of Platform View type: [XvGWvxQbgkeDVg==] may not be set. Defaulting to `width: 100%`. Set `style.width` to any appropriate value to stop this message.

Thank you for the comment. I have updated the plugin to work with web instead of HTML, and the dimensions are now required. If you use .expand, the height and width will expand to the parent widget. 

Best regards.
