### ISSUE TITLE
Firebase storage image is not showing

### ISSUE THREAD

**Issue by moinkhan780** [nycm1989/nImagePicker#2]
When i pass firebase storage image url its not showing. Instead red icon is showing.

**Comment by nycm1989** [comment]
> When i pass firebase storage image url its not showing. Instead red icon is showing.

If the image server has CORS security on the web and your code doesn't include the headers accepted by the server, it will return an error. It's important to note that CORS security includes a registry of accepted IPs in the backend, and if your project is not on the list, even if it has the correct headers, the image will not be displayed.

If your project is on the allowed CORS list, there shouldn't be any issues. I'll be checking if there are problems with specific services like Firebase. If you find the issue, could you help me with a pull request? I'd give you credit for the help.

**Comment by moinkhan780** [comment]
@nycm1989 Ah ok will look into it.
